package cep;

import com.ftn.sbnz.model.events.SharkEvent

declare AlarmTriggered
    sharkId: Long
end

rule "3 appearances of the same shark"
    when
        $t1: SharkEvent($sId: sharkId)
        Number(intValue >= 3) from accumulate(
            $t2: SharkEvent(
                this != $t1, 
                sharkId == $sId, 
                this after[0s, 1h] $t1
            ),
            count($t2)
        )
        not AlarmTriggered(sharkId == $sId)
    then
        insert(new AlarmTriggered($sId));
end

rule "alarm"
    when
        $t1: AlarmTriggered($sId: sharkId);
    then
        System.out.println("ALARM ALARM ALARM!!!");
end
